config/routes.rb
Rails.application.routes.draw do

  get 'dashboard', to: 'users#show', as: 'dashboard'
  devise_for :users
  root to: 'pages#home'

  resources :flats, only: [:index, :new, :show, :create] do
    resources :reviews, only: [:new, :create]
    resources :bookings, only: [:new, :create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :flat

  def total_price
    (end_date - start_date).to_i * flat.price
  end
end

app/models/flat.rb
class Flat < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :reviews

  has_many_attached :photos

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model
  pg_search_scope :search_by_name_and_address,
                  against: %i[name address],
                  using: {
                    tsearch: { prefix: true }
                  }

  def average_rating
    sum = 0
    reviews.each { |review| sum += review.rating }
    sum / reviews.length if reviews.any?
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :flat

  validates :rating, inclusion: { in: 1..5 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :flats
  has_many :bookings
  has_many :reviews, through: :orders

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
  end

  def new
    @booking = Booking.new
    @flat = Flat.find(params[:flat_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @flat = Flat.find(params[:flat_id])
    @booking.flat = @flat
    @booking.user = current_user
    if @booking.save
      redirect_to dashboard_path
    else
      render 'new'
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    if params[:query].present?
      @flats = Flat.search_by_name_and_address(params[:query])
    else
      @flats = Flat.all
    end
      @markers = @flats.geocoded.map do |flat|
      {
        lat: flat.latitude,
        lng: flat.longitude
      }
    end
  end

  def show
    @flat = Flat.find(params[:id])
    @booking = Booking.new
    @review = Review.new
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.user = current_user
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render 'new'
    end
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :price, :description, :user_id, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

    BACKGROUNDS = [
    'https://images.unsplash.com/photo-1495442358998-961b69f45703?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2448&q=80',
    'https://images.unsplash.com/photo-1464082354059-27db6ce50048?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2550&q=80',
    'https://images.unsplash.com/photo-1559139061-28d9de44e40e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=3150&q=80']

  def home
    @random_image = BACKGROUNDS.sample
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_flat, only: %i[ new create ]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.flat = @flat
    if @review.save
      redirect_to flat_path(@flat)
    else
      render 'new'
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end

  def set_flat
    @flat = Flat.find(params[:flat_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @flats = current_user.flats
    @bookings = current_user.bookings
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="container mt-5">
  <h1 class="text-center">Add a new booking</h1>

  <%= simple_form_for [@flat, @booking] do |f| %>
    <%= f.input :start_date %>
    <%= f.input :end_date %>
    <%= f.submit class: 'btn btn-pink' %>
  <% end %>
</div>

app/views/flats/index.html.erb
<div class="container-fluid mt-2">
  <div class="row">
    <div class="col-md-7">
      <h1>All flats</h1>
      <% @flats.each do |flat| %>
        <%= link_to flat_path(flat) do %>
          <hr>
          <div class="card-flat">
            <%= cl_image_tag flat.photos.first.key %>
            <div class="card-flat-infos">
              <p><%= flat.address %></p>
              <h2><%= flat.name %></h2>
              <p><%= flat.description %> </p>
              <p><strong>£<%= flat.price %> per night</strong></p>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="col-md-5">
      <%= form_tag flats_path, class: "form-inline", method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control flex-grow-1",
          placeholder: "Find a flat"
        %>
        <%= submit_tag "Search", id: 'btn-search', class: "btn btn-pink" %>
      <% end %>

    <div id="map"
     style="width: 100%; height: 720px; margin-top: 17px; position:sticky;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
    </div>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container mt-5">
  <h1 class="text-center">Add a new flat</h1>

  <%= simple_form_for(@flat) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :price %>
    <%= f.input :description %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.submit class: 'btn btn-pink' %>
  <% end %>
</div>

app/views/flats/show.html.erb
<div class="container mt-3">

  <h1><%= @flat.name %> </h1>
  <p>
    <strong><%= @flat.address %></strong> | £<%= @flat.price %> per night
    <% if @flat.average_rating %>
      <% @flat.average_rating.times do %>
        <i class="fas fa-star"></i>
        <% end %>
    <% end %>
  </p>
  <div class="row">
    <div class="col-sm-8">
      <div class="card-carousel">
        <%= render 'shared/carousel' %>
        <p class="mt-3"><%= @flat.description %></p>
        <% if @flat.reviews.any? %>
          <h3>Reviews </h3>
          <% @flat.reviews.each do |review| %>
            <li class="mb-1">
              <p>
                <% review.rating.times do %>
                <i class="fas fa-star"></i>
                <% end %>
                <span class='ml-1'><%= review.content %></span>
              </p>
            </li>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="col-sm-4">
      <h2>Book this flat</h2>
      <%= simple_form_for [@flat, @booking] do |f| %>
        <%= f.input :start_date %>
        <%= f.input :end_date %>
        <%= f.submit class: 'btn btn-pink' %>
      <% end %>

      <h3 class="mt-5">Add a review</h3>
      <%= simple_form_for [@flat, @review] do |f| %>
        <%= f.input :rating, collection: 1..5, as: :radio_buttons,             collection_wrapper_tag: 'div',
        collection_wrapper_class: 'category-wrapper',
        item_wrapper_class: 'category-item',
        input_html: {class: 'category-selector'} %>
        <%= f.input :content %>
        <%= f.submit class: 'btn btn-pink' %>
      <% end %>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<%= content_for(:navbar_class, "navbar-home") %>

<div class="banner-landing">
  <img id="banner" alt="" src=<%= @random_image %> >

  <div class="banner-landing-text">
    <h1>Live anywhere</h1>
    <p>Rent awesome flats</p>
    <%= link_to 'Get started', flats_path, class: 'btn btn-pink'  %>
  </div>
</div>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<h1>Add a new review</h1>

<%= simple_form_for [@flat, @review] do |f| %>
  <%= f.input :rating, as: :radio_buttons %>
  <%= f.input :content %>
  <%= f.submit class: 'btn btn-pink' %>
<% end %>

app/views/shared/_carousel.html.erb
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <% @flat.photos.each do |photo| %>
      <div class="carousel-item <%= " active" if photo == @flat.photos.first %>">
        <%= cl_image_tag photo.key, class: "carousel-image d-block w-100" %>
      </div>
    <% end %>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_flat_card.html.erb
<% @flats.each do |flat| %>
    <%= link_to flat_path(flat) do %>
    <hr>
      <div class="card-flat">
        <%= cl_image_tag flat.photos.first.key %>
        <div class="card-flat-infos">
          <p><%= flat.address %></p>
          <h2><%= flat.name %></h2>
          <p><%= flat.description %> </p>
          <p><strong>£<%= flat.price %> per night</strong></p>
          <p>
            <% if flat.average_rating %>
              <% flat.average_rating.times do %>
                <i class="fas fa-star"></i>
              <% end %>
            <% end %>
          </p>
        </div>
      </div>
    <% end %>
  <% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon <%= yield(:navbar_class) %>" >
  <%= link_to "airbnb", root_path, id: "logo" %>
    <%#= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item <%= " active" if current_page?(flats_path) %>">
          <%= link_to "Home", "/flats", class: "nav-link" %>
        </li>
        <li class="nav-item <%= " active" if current_page?(dashboard_path) %>">
          <%= link_to "Dashboard", "/dashboard", class: "nav-link" %>
        </li>
        <li class="nav-item <%= " active" if current_page?(new_flat_path) %>">
          <%= link_to "Add flat", "/flats/new", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://github.com/#{current_user.username}.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Dashboard", "/dashboard", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/show.html.erb
<div class="container mt-3">

  <ul class="list-inline tabs-underlined">
    <li id="tab-flat" class="tab-underlined active">My flats</li>
    <li id="tab-booking" class="tab-underlined">My bookings</li>
  </ul>

  <div class="flats active">
    <%= render 'shared/flat_card' %>
  </div>

  <div class="bookings">
    <% @bookings.each do |booking| %>
      <%= link_to flat_path(booking.flat) do %>
        <hr>
        <div class="card-flat">
          <%= cl_image_tag booking.flat.photos.first.key %>
          <div class="card-flat-infos">
            <p><%= booking.flat.address %></p>
            <h2><%= booking.flat.name %></h2>
            <p>From <%= booking.start_date.strftime('%b %d, %Y') %> to <%= booking.end_date.strftime('%b %d, %Y') %> </p>
            <p><strong>Total price: £<%= booking.total_price %></strong></p>
            <% if booking.flat.average_rating %>
              <p><% booking.flat.average_rating.times do %>
                <i class="fas fa-star"></i>
              <% end %></p>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>